### ISSUE TITLE
Arch Linux PKGBUILD link broken

### ISSUE THREAD

**Issue by progwolff** [free-wheeling/freewheeling#1]
The [link to the Arch Linux PKGBUILD](https://github.com/free-wheeling/freewheeling/wiki/OS-Specific-Packages#ArchLinux_Parabola) is broken.

Compiling from source fails at configure with "error: You need libgnutls11-dev installed".

**Comment by bill-auger** [comment]
yes - it seems arch no longer fully supports gnutls-openssl - this is actually among the main reasons for the move to github - there is currently a dev branch named 'arch' that replaces gnutls with nettle - a new PKGBUILD will be included in the repo once netttle is proved viable and graduates to the master branch - that link on the wiki is currently broken but is anticipating this eventuality

i could add the new PKGBUILD to the arch branch now if you are interested in testing it

**Comment by bill-auger** [comment]
arch/nettle branch with PKGBUILD is now merged into master
