### ISSUE TITLE
freewheeling 0.6.4 doesn't build with fluidsynth 2.0

### ISSUE THREAD

**Issue by dvzrv** [free-wheeling/freewheeling#12]
I currently did a bunch of rebuilds against fluidsynth 2.0.0, which introduces [API changes](http://www.fluidsynth.org/api/index.html#NewIn2_0_0).

This unfortunately breaks building freewheeling 0.6.4:
[freewheeling0.6.4-fluidsynth2.0.txt](https://github.com/free-wheeling/freewheeling/files/2434988/freewheeling0.6.4-fluidsynth2.0.txt)

It would be awesome to make freewheeling compatible to fluidsynth 2.0.0!

**Comment by dvzrv** [comment]
I don't think I'll switch anytime soon. Attempted rebuilds of all dependants, and aside from two, all break.
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/fluidsynth#n6

I think qsynth is already able to support it on git HEAD, but all other projects are either just now starting to work on it (or trying to (re-)move it).

It currently doesn't make sense for me to upgrade, as I'd have to provide two versions of fluidsynth and maintain a hackjob.

However, if more and more projects pick it up in the near future, I'll consider it. From a work-load point of view, I'd rather do an all-or-nothing switch though.

**Comment by dvzrv** [comment]
We're down to only csound not supporting the new API and for that build I will just not use it anymore. Time to implement!

In case you need some insight into how other projects dealt with it:
https://github.com/LMMS/lmms/issues/4640
https://github.com/falkTX/Carla/issues/758
https://github.com/calf-studio-gear/calf/issues/202
https://sourceforge.net/p/qsynth/code/ci/27ac18f496bd9001ee80d519cae757ecff2855f6/log/?path=v

**Comment by bill-auger** [comment]
done 18e9844
