### ISSUE TITLE
ERROR: Can't initialize SDL: No available video device

### ISSUE THREAD

**Issue by piegamesde** [free-wheeling/freewheeling#21]
I can't get freewheeling to run on my system. When I start it, I get

```
FreeWheeling 0.6.6
May we return to the circle.

CORE: Register ringbuffer writer thread: 139898334586944
MAIN: ERROR: Can't initialize SDL: No available video device
EVENT: ERROR- no event type table!
```

This occurs regardless whether I install the Arch package, Nix package or from source.

System information: Arch Linux kernel 5.6.14, Gnome 3.36, Wayland.

**Comment by bill-auger** [comment]
maybe SDL does not work with wayland ?

**Comment by brancomat** [comment]
> maybe SDL does not work with wayland ?

I don't think that's the issue... For what is worth on Fedora 30 with gnome 3.32.2 + Wayland freewheeling works fine, with  a `VIDEO: SDL Ready!` in the logs

**Comment by bill-auger** [comment]
maybe that fedora system has xwayland installed?

i could not find much information about SDL1.2 + wayland - SDL2
apparently has native wayland support, if compiled with the
wayland headers installed; but its not clear if wayland can run
all SDL1 programs - as usual, the arch wiki gives the most
comprehensive advice:

```
To run a SDL2 application on Wayland, set
SDL_VIDEODRIVER=wayland. Note: Many proprietary games come
bundled with old versions of SDL, which don't support Wayland
and might break entirely if you set SDL_VIDEODRIVER=wayland. To
force the application to run with XWayland, set
SDL_VIDEODRIVER=x11.
```

so the suggestion there is to ensure that 'xwayland' is
installed, and start freewheeling like so:

```
$ SDL_VIDEODRIVER=x11 fweelin
```

this is the point where i could insert my standard lecture on why
one should not be running any software, so heavy as a compositor,
on an audio workstation; but lets see how this plays out first

**Comment by piegamesde** [comment]
Yes, `SDL_VIDEODRIVER=x11 fweelin` does work. Apparently I was pretty close with trying `SDL_VIDEODRIVER=wayland` and `SDL_VIDEODRIVER=xorg`, but didn't hit the right value.

Maybe this should be put into the documentation somewhere (troubleshooting section maybe?).

> this is the point where i could insert my standard lecture on why
one should not be running any software, so heavy as a compositor

I'm not running on an audio workstation, it's just some laptop for toying around. :)

**Comment by bill-auger** [comment]
i added a note about this on the troubleshooting and FAQ wiki articles

@piegamesde -

FWIW, it is usually best to report bugs to your distro package maintainer - i am discussing this with the arch maintainer now

which compositor are you running? is it 'sway' ?

**Comment by piegamesde** [comment]
No, Gnome uses Mutter.
