### ISSUE TITLE
Freewheeling doesn't start most of the time

### ISSUE THREAD

**Issue by magnetophon** [free-wheeling/freewheeling#8]
When I run `fweelin`, sometimes it starts, but mostly it says:
```
FreeWheeling 0.6.3
May we return to the circle.

CORE: Register ringbuffer writer thread: 140262730411648
CORE: Register ringbuffer #0: 0x19c9590
MEMMGR: Stacksize: 131072.
CORE: Register ringbuffer writer thread: 140262729750272
CORE: RingBuffer 0x19c9590: Update reader and writer threads to 2
CORE: ERROR: SRMWRingBuffer thread count mismatch.
MEM: Memory manager thread (p0)
```
and drops me back in the shell.

Some googling [suggested](https://sourceforge.net/p/freewheeling/mailman/message/28454157/) this is an intermittent issue, otherwise I wouldn't have thought of just running it over and over again.

Also, it has been there since 2011.

**Comment by bill-auger** [comment]
@kayosiii -

this looks similar to threading issue you patched on your fork - do you think your patch could help this user ? if so, please do send a PR explaining what is the cause of the problem and how your patch fixes it - if this solves both yours and  magnetophon's problem and does not introduce any new problems then it is surely valuable to include

**Comment by bill-auger** [comment]
v0.6.6 fixes this - i believe it was the last known bug remaining

**Comment by magnetophon** [comment]
When I run 0.6.6,I get:
```
FreeWheeling 0.6.5
May we return to the circle.

CORE: Register ringbuffer writer thread: 139882607404544
CORE: Register ringbuffer #0: 0xba6e80
MEMMGR: Stacksize: 131072.
CORE: Register ringbuffer writer thread: 139882387281664
CORE: RingBuffer 0xba6e80: Update reader and writer threads to 2
MEM: Memory manager thread (p0)
CORE: ERROR: SRMWRingBuffer thread count mismatch.
```

**Comment by bill-auger** [comment]
did you compile this yourself or install a binary package? - it
appears that you have v0.6.5

the string '0.6.5' is not in any file of the master branch or
release the source-ball

if you had a previous build, maybe you need to run  `make clean`
first

**Comment by magnetophon** [comment]
I compiled myself.
While it's true that 0.6.5 doesn't appear anywhere in the source, neither does 0.6.6: https://github.com/free-wheeling/freewheeling/search?q=0.6.6&unscoped_q=0.6.6

I built from a clean source tree.

**Comment by bill-auger** [comment]
the version number is in the ./configure script, via configure.ac
- it cascades into the build scripts when you run ./configure -
maybe i missed something; but if the program fails to start,
with that error; im pretty sure that you do not have v0.6.6 -
you could verify, by checking that this patch is applied to
src/fweelin_datatypes.h in your sources

https://github.com/free-wheeling/freewheeling/commit/b5eb2336bd0dd886f0789b2c3a8fff41bf5926a9

**Comment by magnetophon** [comment]
I built again, from that exact commit, and still get 0.6.5.

I'm using NixOS, so I'm not actually manually building, but instead specifying the source, dependencies and build steps in a file, and build from that.
This ensures, among other things, a clean build every time.

I also built d8a604be4cda4af6ac37aa71040e4177829c0ffb; the last commit for 0.6.6.
Same result.

What can I do to troubleshoot further?

**Comment by bill-auger** [comment]
i think you will find that if you checkout the git repo on the
command line, and compile manually on the command line that
everything rocks sweetly - i just did that again myself to make
sure - also, arch has already upgraded, and that package is fine

if it is related to the nix build tools; i can not offer much
advice - try it on a clean system maybe, like in a VM - maybe
your symlink forest could use some weed-whacking; though
i dont know how to do that

**Comment by bill-auger** [comment]
also, the last i knew, there was a nixos package for
freewheeling - if thats still the case, you could just
poke its maintainer to upgrade it for all nixos users

**Comment by magnetophon** [comment]
I am upgrading the package, with the purpose of upstreaming my changes.
Making/changing a package is the way you normally build binaries in NixOS.
I maintain lots of audio software packages for NixOS.

**Comment by bill-auger** [comment]
the only other thing i can suggest off-hand is to run autoreconf
-fi
